env:
  - EMACS=emacs23
  - EMACS=emacs24
before_install:
  # PPA for stable Emacs packages
  - sudo add-apt-repository -y ppa:cassou/emacs
  # PPA for Automake 1.12
  - sudo add-apt-repository -y ppa:dns/gnu
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox texinfo automake
script:
  - emacs --version
  - automake --version
  - autoreconf -i
  - ./configure
  - make all
  - make check VERBOSE=yes
